version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    restart: always
  frontend:
    build: ./front-end-nextjs
    ports:
      - "3000:3000"
    restart: always
